// lib/exportPayslips.ts
// Generates and downloads payslips as a printable HTML file
// No external library needed — uses browser's built-in print

export function exportPayslips(
  payrollLines: any[],
  period: string,
  orgName: string,
  currency: string = 'KES'
) {
  const fmt = (n: number) =>
    `${currency} ${Math.abs(n).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`

  const slips = payrollLines.map(l => {
    const name = l.employee?.contact?.name || 'Employee'
    const empNo = l.employee?.employee_number || '—'
    const dept  = l.employee?.department || '—'
    const title = l.employee?.job_title || '—'

    return `
    <div class="slip">
      <div class="slip-header">
        <div>
          <h2>${orgName}</h2>
          <p class="period">Payslip — ${period}</p>
        </div>
        <div class="right">
          <p class="emp-name">${name}</p>
          <p class="emp-detail">${empNo} · ${dept}</p>
          <p class="emp-detail">${title}</p>
        </div>
      </div>

      <table>
        <thead>
          <tr><th>Earnings</th><th class="amount">Amount</th></tr>
        </thead>
        <tbody>
          <tr><td>Basic Salary</td><td class="amount">${fmt(l.basic_pay)}</td></tr>
          <tr class="total-row"><td><strong>Gross Pay</strong></td><td class="amount"><strong>${fmt(l.gross_pay)}</strong></td></tr>
        </tbody>
      </table>

      <table style="margin-top:12px">
        <thead>
          <tr><th>Deductions</th><th class="amount">Amount</th></tr>
        </thead>
        <tbody>
          <tr><td>PAYE</td><td class="amount deduct">(${fmt(l.paye)})</td></tr>
          <tr><td>NHIF</td><td class="amount deduct">(${fmt(l.nhif)})</td></tr>
          <tr><td>NSSF</td><td class="amount deduct">(${fmt(l.nssf)})</td></tr>
          <tr class="total-row"><td><strong>Total Deductions</strong></td><td class="amount deduct"><strong>(${fmt(l.paye + l.nhif + l.nssf)})</strong></td></tr>
        </tbody>
      </table>

      <div class="net-pay">
        <span>NET PAY</span>
        <span>${fmt(l.net_pay)}</span>
      </div>

      <div class="footer">
        <p>This is a computer-generated payslip and requires no signature.</p>
        <p>Generated by FinAI on ${new Date().toLocaleDateString('en-KE', { year:'numeric', month:'long', day:'numeric' })}</p>
      </div>
    </div>
    `
  }).join('<div class="page-break"></div>')

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Payslips — ${period}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 13px; background: #f5f5f5; color: #333; }

    .slip {
      background: white;
      max-width: 680px;
      margin: 32px auto;
      padding: 32px;
      border-radius: 8px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.08);
    }

    .slip-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      padding-bottom: 20px;
      border-bottom: 2px solid #1d4ed8;
      margin-bottom: 20px;
    }

    h2 { font-size: 20px; color: #1d4ed8; font-weight: 700; }
    .period { color: #64748b; margin-top: 4px; font-size: 12px; }
    .right { text-align: right; }
    .emp-name { font-weight: 700; font-size: 15px; color: #0f172a; }
    .emp-detail { color: #64748b; font-size: 12px; margin-top: 2px; }

    table { width: 100%; border-collapse: collapse; }
    th { background: #f8fafc; text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; border-bottom: 1px solid #e2e8f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
    .amount { text-align: right; font-family: monospace; }
    .deduct { color: #dc2626; }
    .total-row td { background: #f8fafc; border-top: 1px solid #e2e8f0; }

    .net-pay {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-top: 16px;
      padding: 14px 16px;
      background: #1d4ed8;
      color: white;
      border-radius: 8px;
      font-weight: 700;
      font-size: 16px;
    }
    .net-pay span:last-child { font-family: monospace; font-size: 18px; }

    .footer {
      margin-top: 20px;
      padding-top: 12px;
      border-top: 1px solid #f1f5f9;
      color: #94a3b8;
      font-size: 11px;
    }
    .footer p { margin-top: 3px; }

    .page-break { page-break-after: always; height: 0; }

    @media print {
      body { background: white; }
      .slip { box-shadow: none; margin: 0; max-width: 100%; border-radius: 0; }
      .page-break { page-break-after: always; }
    }
  </style>
</head>
<body>
  ${slips}
  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>`

  // Open in new tab — browser print dialog handles PDF/paper
  const blob = new Blob([html], { type: 'text/html' })
  const url  = URL.createObjectURL(blob)
  const win  = window.open(url, '_blank')
  if (!win) {
    // Fallback: direct download
    const a = document.createElement('a')
    a.href = url
    a.download = `payslips-${period}.html`
    a.click()
  }
  setTimeout(() => URL.revokeObjectURL(url), 5000)
}
